name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode.app
    
    - name: Build Swift Package
      run: swift build
    
    - name: Run Tests
      run: swift test
    
    - name: Build Example App (SPM)
      run: swift build --product MetalCanvasExample
    
    - name: Build Example App (Xcode)
      run: |
        cd Example
        xcodebuild -project MetalCanvasExample.xcodeproj \
          -scheme MetalCanvasExample \
          -configuration Debug \
          -destination 'platform=macOS' \
          build