name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: macos-15
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode.app
    
    - name: Build Swift Package
      run: swift build
    
    - name: Run Tests
      run: swift test
    
    - name: Build macOS Example App (Xcode)
      run: |
        cd Example
        xcodebuild -workspace MetalCanvasExamples.xcworkspace \
          -scheme MetalCanvasExample \
          -configuration Debug \
          -destination 'platform=macOS' \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          build
    
    - name: Build iOS Example App (Xcode)
      run: |
        cd Example
        xcodebuild -workspace MetalCanvasExamples.xcworkspace \
          -scheme MetalCanvasExample-iOS \
          -configuration Debug \
          -destination 'generic/platform=iOS Simulator' \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          build