name: Deploy DocC

on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: macos-15
    steps:
    - uses: actions/checkout@v4
    
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode.app
    
    - name: Build DocC
      run: |
        # Generate documentation using xcodebuild
        xcodebuild docbuild \
          -scheme MetalCanvas \
          -derivedDataPath ./DerivedData \
          -destination 'platform=macOS'
        
        # Transform the documentation archive for static hosting
        $(xcrun --find docc) process-archive \
          transform-for-static-hosting ./DerivedData/Build/Products/Debug/MetalCanvas.doccarchive \
          --hosting-base-path MetalCanvas \
          --output-path ./docs
    
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./docs

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4